name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux-x86_64
          os: ubuntu-latest
        - name: macOS-aarch64
          os: macos-latest
        - name: macOS-x86_64
          os: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: |
        echo "::group::Install Linux software"
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15 all
    - name: Build and Test lean-cvc5
      uses: leanprover/lean-action@v1
      with:
        use-github-cache: false
